@SuperHeroApi-DotNet8_HostAddress = https://localhost:7146
@SuperHeroApi_DotNet8_HostAddress = http://localhost:5280

GET {{SuperHeroApi_DotNet8_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{SuperHeroApi-DotNet8_HostAddress}}/weatherforecast

###

POST {{SuperHeroApi-DotNet8_HostAddress}}/api/superhero
Content-Type: application/json

{
  //SuperHero
}

###
